export const GET_PDF_FOLDER_STRUCTURE_REQUEST = "GET_PDF_FOLDER_STRUCTURE_REQUEST";
export const GET_PDF_FOLDER_STRUCTURE_SUCCESS = "GET_PDF_FOLDER_STRUCTURE_SUCCESS";
export const GET_PDF_FOLDER_STRUCTURE_FAILURE = "GET_PDF_FOLDER_STRUCTURE_FAILURE";
export const UPDATE_FILE = "UPDATE_FILE";
export const DISPLAY_IMAGE = "DISPLAY_IMAGE";
export const CHANGE_SEARCH_TEMPLATE = "CHANGE_SEARCH_TEMPLATE";
export const CLEAR_FILE_FOLDER_DATA = "CLEAR_FILE_FOLDER_DATA";
